version: '3.8'

services:
    mysql:
        image: mysql:8.0.23
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 1qaz@WSX
        ports:
            - 7306:3306
        volumes:
            - mysql_event_data:/var/lib/mysql

    postgres:
        image: postgres:13.1
        restart: always
        environment:
            POSTGRES_PASSWORD: 1qaz@WSX
        ports:
            - 7432:5432
        volumes:
            - postgres_event_data:/var/lib/postgresql/data

    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 7080:8080

volumes:
    mysql_event_data:
    postgres_event_data:
